server:
  port: 8080    #配置tomcat启动端口号
spring:
  application:
    name: reggie_take_out     #指定应用名称，默认是项目名
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: 192.168.10.133
    password: wzsallp5201314
    database: 0
    port: 6379
  cache:
    redis:
      time-to-live: 1800000  #设置缓存过期时间,单位为毫秒
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #使用默认日志
    use-generated-keys: true
  global-config:
    db-config:
      id-type: ASSIGN_ID        #雪花算法
reggie:
  path: D:\\upload\